# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VENTANA.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(775, 663)
        Form.setMaximumSize(QtCore.QSize(1111, 904))
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(9, 9, 711, 601))
        self.mdiArea.setObjectName("mdiArea")
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 22))
        self.menubar.setNativeMenuBar(False)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuUSUARIOS = QtWidgets.QMenu(self.menubar)
        self.menuUSUARIOS.setObjectName("menuUSUARIOS")
        self.menuTABLAS = QtWidgets.QMenu(self.menubar)
        self.menuTABLAS.setObjectName("menuTABLAS")
        self.menuBASES_DE_DATOS = QtWidgets.QMenu(self.menubar)
        self.menuBASES_DE_DATOS.setObjectName("menuBASES_DE_DATOS")
        self.menuAYUDA = QtWidgets.QMenu(self.menubar)
        self.menuAYUDA.setObjectName("menuAYUDA")
        Form.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(Form)
        self.toolBar.setObjectName("toolBar")
        Form.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(Form)
        self.toolBar_2.setObjectName("toolBar_2")
        Form.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionUSUARIO = QtWidgets.QAction(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Img/valor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUSUARIO.setIcon(icon)
        self.actionUSUARIO.setObjectName("actionUSUARIO")
        self.actionSALIR = QtWidgets.QAction(Form)
        self.actionSALIR.setObjectName("actionSALIR")
        self.actionServicios = QtWidgets.QAction(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Img/entrega-rapida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionServicios.setIcon(icon1)
        self.actionServicios.setObjectName("actionServicios")
        self.actionVIAJES = QtWidgets.QAction(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Img/libro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVIAJES.setIcon(icon2)
        self.actionVIAJES.setObjectName("actionVIAJES")
        self.actionPAGOS = QtWidgets.QAction(Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Img/pagos_icono.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPAGOS.setIcon(icon3)
        self.actionPAGOS.setObjectName("actionPAGOS")
        self.actionCLIENTES = QtWidgets.QAction(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Img/CLIENTE.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCLIENTES.setIcon(icon4)
        self.actionCLIENTES.setObjectName("actionCLIENTES")
        self.actionEMPLEADOS = QtWidgets.QAction(Form)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Img/empleado-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEMPLEADOS.setIcon(icon5)
        self.actionEMPLEADOS.setObjectName("actionEMPLEADOS")
        self.actionUNIDADES = QtWidgets.QAction(Form)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Img/camion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUNIDADES.setIcon(icon6)
        self.actionUNIDADES.setObjectName("actionUNIDADES")
        self.actionOFICINAS = QtWidgets.QAction(Form)
        self.actionOFICINAS.setObjectName("actionOFICINAS")
        self.actionRESPALDOS = QtWidgets.QAction(Form)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Img/base-de-datos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRESPALDOS.setIcon(icon7)
        self.actionRESPALDOS.setObjectName("actionRESPALDOS")
        self.actionTUTORIAL = QtWidgets.QAction(Form)
        self.actionTUTORIAL.setObjectName("actionTUTORIAL")
        self.actionInicio = QtWidgets.QAction(Form)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Img/carrera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInicio.setIcon(icon8)
        self.actionInicio.setObjectName("actionInicio")
        self.actionAGREGAR = QtWidgets.QAction(Form)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Img/mas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAGREGAR.setIcon(icon9)
        self.actionAGREGAR.setObjectName("actionAGREGAR")
        self.actionEDITAR = QtWidgets.QAction(Form)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Img/lapiz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEDITAR.setIcon(icon10)
        self.actionEDITAR.setObjectName("actionEDITAR")
        self.actionELIMINAR = QtWidgets.QAction(Form)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Img/salida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionELIMINAR.setIcon(icon11)
        self.actionELIMINAR.setObjectName("actionELIMINAR")
        self.action = QtWidgets.QAction(Form)
        self.action.setObjectName("action")
        self.menu.addAction(self.actionInicio)
        self.menuUSUARIOS.addAction(self.actionUSUARIO)
        self.menuUSUARIOS.addSeparator()
        self.menuUSUARIOS.addAction(self.actionSALIR)
        self.menuTABLAS.addAction(self.actionServicios)
        self.menuTABLAS.addAction(self.actionVIAJES)
        self.menuTABLAS.addAction(self.actionPAGOS)
        self.menuTABLAS.addAction(self.actionCLIENTES)
        self.menuTABLAS.addAction(self.actionEMPLEADOS)
        self.menuTABLAS.addAction(self.actionUNIDADES)
        self.menuTABLAS.addAction(self.actionOFICINAS)
        self.menuBASES_DE_DATOS.addAction(self.actionEDITAR)
        self.menuBASES_DE_DATOS.addSeparator()
        self.menuBASES_DE_DATOS.addAction(self.actionAGREGAR)
        self.menuBASES_DE_DATOS.addAction(self.actionELIMINAR)
        self.menuBASES_DE_DATOS.addSeparator()
        self.menuBASES_DE_DATOS.addAction(self.actionRESPALDOS)
        self.menuAYUDA.addAction(self.actionTUTORIAL)
        self.menuAYUDA.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuUSUARIOS.menuAction())
        self.menubar.addAction(self.menuTABLAS.menuAction())
        self.menubar.addAction(self.menuBASES_DE_DATOS.menuAction())
        self.menubar.addAction(self.menuAYUDA.menuAction())
        self.toolBar.addAction(self.actionInicio)
        self.toolBar.addAction(self.actionCLIENTES)
        self.toolBar.addAction(self.actionEMPLEADOS)
        self.toolBar.addAction(self.actionAGREGAR)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.menu.setTitle(_translate("Form", "."))
        self.menuUSUARIOS.setTitle(_translate("Form", "USUARIOS"))
        self.menuTABLAS.setTitle(_translate("Form", "TABLAS"))
        self.menuBASES_DE_DATOS.setTitle(_translate("Form", "BASES DE DATOS"))
        self.menuAYUDA.setTitle(_translate("Form", "AYUDA"))
        self.toolBar.setWindowTitle(_translate("Form", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("Form", "toolBar_2"))
        self.actionUSUARIO.setText(_translate("Form", "USUARIO"))
        self.actionSALIR.setText(_translate("Form", "SALIR"))
        self.actionServicios.setText(_translate("Form", "SERVICIOS"))
        self.actionVIAJES.setText(_translate("Form", "VIAJES"))
        self.actionPAGOS.setText(_translate("Form", "PAGOS"))
        self.actionCLIENTES.setText(_translate("Form", "CLIENTES"))
        self.actionEMPLEADOS.setText(_translate("Form", "EMPLEADOS"))
        self.actionUNIDADES.setText(_translate("Form", "UNIDADES"))
        self.actionOFICINAS.setText(_translate("Form", "OFICINAS"))
        self.actionRESPALDOS.setText(_translate("Form", "RESPALDOS"))
        self.actionTUTORIAL.setText(_translate("Form", "TUTORIAL"))
        self.actionInicio.setText(_translate("Form", "INICIO"))
        self.actionAGREGAR.setText(_translate("Form", "AGREGAR"))
        self.actionEDITAR.setText(_translate("Form", "EDITAR "))
        self.actionELIMINAR.setText(_translate("Form", "ELIMINAR"))
        self.action.setText(_translate("Form", "?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
